# Generated by Django 2.1.1 on 2018-09-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180917_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Updated_Date',
            new_name='Updated',
        ),
        migrations.AlterField(
            model_name='product',
            name='Created',
            field=models.DateTimeField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Created',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
